services:
  web:
    image: linkstackorg/linkstack:latest
    container_name: linkstack_web
    ports:
      - "80:80"
    environment:
      # Application settings
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:random_key
      - APP_URL=${SERVICE_FQDN_LINKSTACK:-http://localhost}
      # Database configuration
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=linkstack
      - DB_USERNAME=${SERVICE_USER_DB:-linkstack_user}
      - DB_PASSWORD=${SERVICE_PASSWORD_DB}
      - DB_PREFIX=linkstack_
      # Cache and session drivers
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - linkstack_data:/htdocs
    user: apache:apache
    networks:
      - linkstack_net

  db:
    image: mysql:8.0
    container_name: linkstack_db
    ports:
      - "3306:3306"
    environment:
      # MySQL configuration using Coolify-generated passwords
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQL_ROOT}
      - MYSQL_DATABASE=linkstack
      - MYSQL_USER=${SERVICE_USER_DB:-linkstack_user}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DB}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - linkstack_net

  redis:
    image: redis:6-alpine
    container_name: linkstack_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${SERVICE_PASSWORD_REDIS}"]
    environment:
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 -a $${REDIS_PASSWORD} ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - linkstack_net

volumes:
  linkstack_data:
  db_data:

networks:
  linkstack_net:
