version: '3.8'

services:
  web:
    image: linkstackorg/linkstack:latest
    container_name: linkstack_web
    ports:
      - "80:80"
    environment:
      # Application settings
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:random_key
      - APP_URL=${SERVICE_FQDN_LINKSTACK:-http://localhost}
      # Database configuration
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=linkstack
      - DB_USERNAME=${SERVICE_USER_DB:-linkstack_user}
      - DB_PASSWORD=${SERVICE_PASSWORD_DB:-linkstack_password}
      - DB_PREFIX=linkstack_
      # Cache and session drivers
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - linkstack_data:/htdocs
    user: apache:apache
    networks:
      - linkstack_net

  db:
    image: mysql:8.0
    container_name: linkstack_db
    ports:
      - "3306:3306"
    environment:
      # MySQL configuration
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQL_ROOT:-root_password}
      - MYSQL_DATABASE=linkstack
      - MYSQL_USER=${SERVICE_USER_DB:-linkstack_user}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DB:-linkstack_password}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - linkstack_net

volumes:
  linkstack_data:
  db_data:

networks:
  linkstack_net:
