services:
  web:
    build: .
    container_name: linkstack_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:random_key
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=linkstack
      - DB_USERNAME=root_user
      - DB_PASSWORD=root_password
      - DB_PREFIX=linkstack_
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: linkstackdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=linkstack
      - MYSQL_USER=root_user
      - MYSQL_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
